### ISSUE TITLE
Final API changes

### ISSUE THREAD

**Issue by kushalkolar** [nel-lab/mesmerize-core#44]
- [x] all data that relates to an item should be in a dir named using the uuid for that item. - Done in #51 

- [x] add_item: params could be chunked by step. - done in #50 , algo params get put in `"main"` key allowing room to add more keys for other things like `Ain` matrix etc.

- [x] caiman.run() needs to only take `backend` as `arg` and rest are optional `kwargs`. `_run_subprocess` only takes `runfile_path` as an `arg`. Remove the callbacks args from everything, it should be passed as a kwarg only within the napari stuff for QProcess and therefore removed from mesmerize-core.

- [x] add comments as default column

cnmf:
- [x] getting the dfof array. It can take kwargs to pass to the caiman dfof function. If dfof has already been calculated with the given kwargs, it just returns those, (perhaps just using the cache). If new kwargs are provided it will use the caiman function to calculate them and then return the dfof vals @kushalkolar 
- [x] reconstructed movie, pass idx_components, also allow passing a single integer to `ixs_frames` for getting a single frame @clewis7 
- [x] get_reconstructed_background() @clewis7 
- [x] get_residuals() @clewis7 
- [x] evaluate_components() @kushalkolar #20 
- [x] #69

general:
- [x] test on windows

**Comment by kushalkolar** [comment]
Demo notebooks for extensions in more detail.
